name: portfolio-ruan
regions:
  - fra
services:
  - name: app
    ports:
      - port: 5000
        http: http
    routes:
      - path: /
        handlers:
          - type: http
            service: app
    env:
      - name: NODE_ENV
        value: production
    instance:
      type: nano
    buildpacks:
      nodejs:
        enabled: true
    health_check:
      path: /
      timeout: 10
    scaling:
      min: 1
      max: 1
    build:
      command: npm install && npm run build
    run:
      command: npm start